server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # บรรทัดนี้สำคัญมาก! ทำหน้าที่ส่งทุก URL กลับไปที่ index.html
        try_files $uri $uri/ /index.html; 
    }
}