// src/app/layout.js
import { AuthProvider } from './contexts/AuthContext'; 
import Header from './components/Header';

export const metadata = {
  title: 'Baan Joy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider> {/* <-- 1. ครอบทั้งหมดด้วย AuthProvider */}
          <Header />       {/* <-- 2. Header และ main อยู่ข้างใน */}
          <main>{children}</main> 
        </AuthProvider>
      </body>
    </html>
  );
}